"use client";

import { useState, useTransition } from "react";
import {
  Clapperboard,
  GalleryThumbnails,
  Hash,
  Loader2,
  type LucideIcon,
  Megaphone,
  Music2,
  Quote,
  RefreshCw,
  Smartphone,
  Sparkles,
  Wand2,
} from "lucide-react";
import { toast } from "sonner";

import { generateContent } from "@/app/dashboard/(panel)/studio/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  STUDIO_PLATFORMS,
  STUDIO_THEMES,
  PLATFORM_LABEL,
  type HashtagSet,
  type StudioContent,
  type StudioPlatform,
} from "@/components/studio/studio-types";
import { CopyButton } from "@/components/studio/copy-button";
import { cn } from "@/lib/utils";

const PLATFORM_ICON: Record<StudioPlatform, LucideIcon> = {
  instagram_post: GalleryThumbnails,
  instagram_reel: Clapperboard,
  instagram_story: Smartphone,
};

export function ContentStudio({ aiLive }: { aiLive: boolean }) {
  const [theme, setTheme] = useState("");
  const [activePreset, setActivePreset] = useState<string | null>(null);
  const [platform, setPlatform] = useState<StudioPlatform>("instagram_reel");
  const [content, setContent] = useState<StudioContent | null>(null);
  const [source, setSource] = useState<"ai" | "template" | null>(null);
  const [pending, startTransition] = useTransition();

  function pickPreset(presetValue: string, presetPrompt: string) {
    setActivePreset(presetValue);
    setTheme(presetPrompt);
  }

  function run() {
    const t = theme.trim();
    if (!t) {
      toast.error("Pick or type a theme to generate.");
      return;
    }
    startTransition(async () => {
      const res = await generateContent({ theme: t, platform });
      if (!res.ok) {
        toast.error(res.message);
        return;
      }
      setContent(res.content);
      setSource(res.source);
      toast.success(
        res.source === "ai"
          ? "Content generated by AI"
          : "Content drafted — add an API key for AI variety",
      );
    });
  }

  const ReelLabelIcon = PLATFORM_ICON[platform];

  return (
    <div className="grid gap-6 lg:grid-cols-[minmax(0,360px)_minmax(0,1fr)] lg:items-start">
      {/* ---- Composer ---- */}
      <Card className="border-border/70 lg:sticky lg:top-6">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <Wand2 className="size-4 text-primary" />
            Compose
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="space-y-2">
            <p className="text-xs font-medium text-muted-foreground">
              What are we showing off?
            </p>
            <div className="grid grid-cols-2 gap-2">
              {STUDIO_THEMES.map((preset) => {
                const Icon = preset.icon;
                const active = activePreset === preset.value;
                return (
                  <button
                    key={preset.value}
                    type="button"
                    onClick={() => pickPreset(preset.value, preset.prompt)}
                    className={cn(
                      "flex items-center gap-2 rounded-lg border px-2.5 py-2 text-left text-xs font-medium transition-colors",
                      active
                        ? "border-primary/50 bg-primary/10 text-primary"
                        : "border-border/70 text-foreground hover:bg-accent",
                    )}
                  >
                    <Icon className="size-3.5 shrink-0" />
                    <span className="truncate">{preset.label}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-xs font-medium text-muted-foreground">
              Or describe your own theme
            </p>
            <Input
              value={theme}
              onChange={(e) => {
                setTheme(e.target.value);
                setActivePreset(null);
              }}
              placeholder="e.g. Poolside cocktail mehndi at sunset"
              className="h-9"
            />
          </div>

          <div className="space-y-2">
            <p className="text-xs font-medium text-muted-foreground">Format</p>
            <div className="grid gap-2">
              {STUDIO_PLATFORMS.map((p) => {
                const Icon = PLATFORM_ICON[p.value];
                const active = platform === p.value;
                return (
                  <button
                    key={p.value}
                    type="button"
                    onClick={() => setPlatform(p.value)}
                    className={cn(
                      "flex items-center gap-2.5 rounded-lg border px-3 py-2 text-left transition-colors",
                      active
                        ? "border-primary/50 bg-primary/10"
                        : "border-border/70 hover:bg-accent",
                    )}
                  >
                    <span
                      className={cn(
                        "flex size-7 items-center justify-center rounded-md",
                        active
                          ? "bg-primary/15 text-primary"
                          : "bg-muted text-muted-foreground",
                      )}
                    >
                      <Icon className="size-4" />
                    </span>
                    <span className="min-w-0">
                      <span
                        className={cn(
                          "block text-sm font-medium",
                          active && "text-primary",
                        )}
                      >
                        {p.label}
                      </span>
                      <span className="block text-xs text-muted-foreground">
                        {p.hint}
                      </span>
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          <Button
            type="button"
            onClick={run}
            disabled={pending}
            className="w-full"
          >
            {pending ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Sparkles className="size-4" />
            )}
            {content ? "Regenerate" : "Generate content"}
          </Button>

          <p className="text-center text-xs text-muted-foreground">
            {aiLive
              ? "Powered by Claude · always review before posting"
              : "Demo mode · add ANTHROPIC_API_KEY for live AI"}
          </p>
        </CardContent>
      </Card>

      {/* ---- Results ---- */}
      <div className="space-y-5">
        {!content ? (
          <EmptyStudio pending={pending} />
        ) : (
          <>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <Badge variant="secondary" className="gap-1.5">
                  <ReelLabelIcon className="size-3" />
                  {PLATFORM_LABEL[platform]}
                </Badge>
                <Badge
                  variant={source === "ai" ? "default" : "outline"}
                  className="gap-1.5"
                >
                  <Sparkles className="size-3" />
                  {source === "ai" ? "AI generated" : "Smart template"}
                </Badge>
              </div>
              <Button
                type="button"
                size="sm"
                variant="ghost"
                onClick={run}
                disabled={pending}
              >
                {pending ? (
                  <Loader2 className="size-3.5 animate-spin" />
                ) : (
                  <RefreshCw className="size-3.5" />
                )}
                Regenerate
              </Button>
            </div>

            <CaptionCard caption={content.caption} cta={content.cta} />
            <HashtagsCard sets={content.hashtagSets} />
            <ReelCard content={content} />
          </>
        )}
      </div>
    </div>
  );
}

function EmptyStudio({ pending }: { pending: boolean }) {
  return (
    <Card className="border-dashed">
      <CardContent className="flex flex-col items-center justify-center gap-3 py-20 text-center">
        <span className="flex size-12 items-center justify-center rounded-full bg-primary/10 text-primary">
          {pending ? (
            <Loader2 className="size-6 animate-spin" />
          ) : (
            <Megaphone className="size-6" />
          )}
        </span>
        <div>
          <p className="font-medium">
            {pending ? "Drafting your content…" : "Your content appears here"}
          </p>
          <p className="mt-0.5 max-w-sm text-sm text-muted-foreground">
            {pending
              ? "Writing a caption, hashtag sets, and a reel shot-list."
              : "Pick a theme and format on the left, then hit Generate to get a caption, hashtag sets, and a reel script."}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

function CaptionCard({ caption, cta }: { caption: string; cta: string }) {
  return (
    <Card className="border-border/70">
      <CardHeader className="flex flex-row items-center justify-between gap-2 pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <Quote className="size-4 text-primary" />
          Caption
        </CardTitle>
        <CopyButton value={caption} label="Copy" toastLabel="Caption" />
      </CardHeader>
      <CardContent className="space-y-3">
        <p className="text-sm whitespace-pre-wrap leading-relaxed">{caption}</p>
        <div className="flex items-start gap-2 rounded-lg border border-border/70 bg-muted/40 px-3 py-2">
          <Megaphone className="mt-0.5 size-3.5 shrink-0 text-primary" />
          <p className="text-sm text-muted-foreground">
            <span className="font-medium text-foreground">CTA:</span> {cta}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

function HashtagsCard({ sets }: { sets: HashtagSet[] }) {
  const all = Array.from(new Set(sets.flatMap((s) => s.tags)));
  return (
    <Card className="border-border/70">
      <CardHeader className="flex flex-row items-center justify-between gap-2 pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <Hash className="size-4 text-primary" />
          Hashtag sets
          <span className="text-sm font-normal text-muted-foreground tabular-nums">
            {all.length}
          </span>
        </CardTitle>
        <CopyButton
          value={all.join(" ")}
          label="Copy all"
          toastLabel="All hashtags"
        />
      </CardHeader>
      <CardContent className="space-y-4">
        {sets.map((set) => (
          <div key={set.label} className="space-y-2">
            <div className="flex items-center justify-between gap-2">
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                {set.label}
              </p>
              <CopyButton
                value={set.tags.join(" ")}
                size="icon"
                variant="ghost"
                label={`Copy ${set.label}`}
                toastLabel={set.label}
              />
            </div>
            <div className="flex flex-wrap gap-1.5">
              {set.tags.map((tag) => (
                <span
                  key={tag}
                  className="rounded-md bg-primary/8 px-2 py-0.5 text-xs font-medium text-primary"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

function ReelCard({ content }: { content: StudioContent }) {
  const script =
    `HOOK: ${content.hook}\n\n` +
    content.shotList
      .map(
        (s) =>
          `${s.time} — ${s.shot}${s.text ? `\n   On-screen: ${s.text}` : ""}`,
      )
      .join("\n\n") +
    `\n\nAudio: ${content.audioSuggestion}`;

  return (
    <Card className="border-border/70">
      <CardHeader className="flex flex-row items-center justify-between gap-2 pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <Clapperboard className="size-4 text-primary" />
          Reel script & shot-list
        </CardTitle>
        <CopyButton value={script} label="Copy script" toastLabel="Reel script" />
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-start gap-2 rounded-lg border border-primary/30 bg-primary/5 px-3 py-2.5">
          <Sparkles className="mt-0.5 size-4 shrink-0 text-primary" />
          <div>
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
              Opening hook
            </p>
            <p className="mt-0.5 text-sm font-medium">{content.hook}</p>
          </div>
        </div>

        <ol className="space-y-3">
          {content.shotList.map((s, i) => (
            <li key={`${s.time}-${i}`} className="flex gap-3">
              <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold tabular-nums text-muted-foreground">
                {i + 1}
              </span>
              <div className="min-w-0 flex-1 border-b border-border/60 pb-3 last:border-0 last:pb-0">
                <p className="text-xs font-medium tabular-nums text-primary">
                  {s.time}
                </p>
                <p className="mt-0.5 text-sm">{s.shot}</p>
                {s.text && (
                  <p className="mt-1 text-xs text-muted-foreground">
                    On-screen: <span className="text-foreground">{s.text}</span>
                  </p>
                )}
              </div>
            </li>
          ))}
        </ol>

        <div className="flex items-start gap-2 rounded-lg border border-border/70 bg-muted/40 px-3 py-2">
          <Music2 className="mt-0.5 size-3.5 shrink-0 text-primary" />
          <p className="text-sm text-muted-foreground">
            <span className="font-medium text-foreground">Audio:</span>{" "}
            {content.audioSuggestion}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
